// <auto-generated />
using System;
using LightsAndBites.Data;
using LightsAndBites.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightsAndBites.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190820133738_ChangedBarTypeToName")]
    partial class ChangedBarTypeToName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightsAndBites.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardPhoto");

                    b.Property<string>("Category");

                    b.Property<int>("CityId");

                    b.Property<int?>("CommentId");

                    b.Property<int>("Dislikes");

                    b.Property<double>("Latitude");

                    b.Property<int>("Likes");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
